export const FETCH_FIGHTERS_START = 'FETCH_FIGHTERS_START'
export const FETCH_FIGHTERS_SUCCESS = 'FETCH_FIGHTERS_SUCCESS'
export const FETCH_FIGHTERS_FAILURE = 'FETCH_FIGHTERS_FAILURE'

export const GET_FIGHTER_BY_ID_START = 'GET_FIGHTER_BY_ID_START'
export const GET_FIGHTER_BY_ID_SUCCESS = 'GET_FIGHTER_BY_ID_SUCCESS'
export const GET_FIGHTER_BY_ID_FAILURE = 'GET_FIGHTER_BY_ID_FAILURE'


