export const FETCH_FIGHTERS_START = 'FETCH_FIGHTERS_START'
export const FETCH_FIGHTERS_SUCCESS = 'FETCH_FIGHTERS_SUCCESS'
export const FETCH_FIGHTERS_FAILURE = 'FETCH_FIGHTERS_FAILURE'

export const FETCH_FIGHTER_BY_ID_START = 'FETCH_FIGHTER_BY_ID_START'
export const FETCH_FIGHTER_BY_ID_SUCCESS = 'FETCH_FIGHTER_BY_ID_SUCCESS'
export const FETCH_FIGHTER_BY_ID_FAILURE = 'FETCH_FIGHTER_BY_ID_FAILURE'
